default: &default
  adapter: mysql2
  host: localhost
  username: root
  password:

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: test

production:
  <<: *default
  database: prod
